name: Yarn Lint Workflow

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: yarn install
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          yarn install
      - run: yarn lint
